apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: cnv-hco-config
  namespace: open-cluster-management
spec:
  agentInstallNamespace: openshift-cnv
  customizedVariables:
  - name: LIVE_NETWORK_KEY
  - name: LIVE_NETWORK_VALUE
