apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: openshift-cnv
  namespace: open-cluster-management-global-set
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            acm/cnv-operator-install: "true"
    - requiredClusterSelector: # This is for "Fleet virtualization" in the console
        labelSelector:
          matchLabels:
            local-cluster: "true"
