apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnTemplate
metadata:
  name: kubevirt-hyperconverged-operator
spec:
  addonName: kubevirt-hyperconverged-operator
  registration:
    - type: CustomSigner
      customSigner:
        signerName: open-cluster-management.io/kubevirt-hyperconverged-addon
        signingCA:
          name: kubevirt-hyperconverged-ca
          namespace: openshift-cnv
  agentSpec:
    workload:
      manifests:
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: Role
          metadata:
            name: operatorpolicy-manager
            namespace: open-cluster-management-policies
          rules:
            - apiGroups: ["hco.kubevirt.io"]
              resources: ["hyperconvergeds"]
              verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
            - apiGroups: ["policy.open-cluster-management.io"]
              resources: ["operatorpolicies"]
              verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: operatorpolicy-manager-hosted-binding
            namespace: open-cluster-management-policies
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: Role
            name: operatorpolicy-manager
          subjects:
            - kind: ServiceAccount
              name: klusterlet-{{CLUSTER_NAME}}-work-sa
              namespace: open-cluster-management-{{CLUSTER_NAME}}
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: operatorpolicy-manager-binding
            namespace: open-cluster-management-policies
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: Role
            name: operatorpolicy-manager
          subjects:
            - kind: ServiceAccount
              name: klusterlet-work-sa
              namespace: open-cluster-management-agent
        - apiVersion: policy.open-cluster-management.io/v1beta1
          kind: OperatorPolicy
          metadata:
            name: kubevirt-hyperconverged-operator
            namespace: open-cluster-management-policies
          spec:
            remediationAction: enforce
            complianceType: musthave
            operatorGroup: # optional
              name: openshift-cnv
              namespace: openshift-cnv
              targetNamespaces:
                  - openshift-cnv
            subscription:
              channel: stable
              name: kubevirt-hyperconverged
              namespace: openshift-cnv
            upgradeApproval: Automatic
            # removalBehavior:                  # This only works if the complianceType: mustnothave
            #   clusterServiceVersions: Delete
            #   customResourceDefinitions: Keep
            #   operatorGroups: DeleteIfUnused
            #   subscriptions: Delete
